recipe_sha: 1f9b8cb531bfc8d03c28ba17f689b69bbf84e81ebcc4aabff6482e6b82560656  # The commit at which this recipe failed to build.
skiplist: true # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
log: |2-
   - r-assertive.sets
   - r-gridextra
   - r-cluster
   - bioconductor-degreport >=1.36.0,<1.37.0
   - r-rlang
   - r-cowplot
   - bioconductor-limma >=3.56.0,<3.57.0
   - r-stringr
   - bioconductor-iranges >=2.34.0,<2.35.0

  with channels:
   - conda-forge
   - bioconda
   - defaults

  The reported errors are:
  - Encountered problems while solving:
  -   - package bioconductor-degreport-1.36.0-r43hdfd78af_0 is excluded by strict repo priority
  -
  Traceback (most recent call last):
    File "/opt/conda/lib/python3.8/site-packages/boa/cli/mambabuild.py", line 141, in mamba_get_install_actions
      solution = solver.solve_for_action(_specs, prefix)
    File "/opt/conda/lib/python3.8/site-packages/boa/core/solver.py", line 244, in solve_for_action
      t = self.solve(specs)
    File "/opt/conda/lib/python3.8/site-packages/boa/core/solver.py", line 234, in solve
      raise RuntimeError("Solver could not find solution."  error_string)
  RuntimeError: Solver could not find solution.Mamba failed to solve:
   - bioconductor-deseq2 >=1.40.0,<1.41.0
   - r-gplots
   - r-ggally
   - r-ggplot2
   - r-tidyr
   - r-dplyr
   - bioconductor-s4vectors >=0.38.0,<0.39.0
   - bioconductor-genomicranges >=1.52.0,<1.53.0
   - bioconductor-biocgenerics >=0.46.0,<0.47.0
   - bioconductor-summarizedexperiment >=1.30.0,<1.31.0
   - r-gtools
   - r-rcolorbrewer
   - bioconductor-annotationdbi >=1.62.0,<1.63.0
   - r-reshape
   - bioconductor-biobase >=2.60.0,<2.61.0
   - r-readr
   - r-base 4.3.*
   - r-broom
   - r-tibble
   - r-assertive.sets
   - r-gridextra
   - r-cluster
   - bioconductor-degreport >=1.36.0,<1.37.0
   - r-rlang
   - r-cowplot
   - bioconductor-limma >=3.56.0,<3.57.0
   - r-stringr
   - bioconductor-iranges >=2.34.0,<2.35.0

  with channels:
   - conda-forge
   - bioconda
   - defaults

  The reported errors are:
  - Encountered problems while solving:
  -   - package bioconductor-degreport-1.36.0-r43hdfd78af_0 is excluded by strict repo priority
  -

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/opt/conda/bin/conda-mambabuild", line 10, in <module>
      sys.exit(main())
    File "/opt/conda/lib/python3.8/site-packages/boa/cli/mambabuild.py", line 256, in main
      call_conda_build(action, config)
    File "/opt/conda/lib/python3.8/site-packages/boa/cli/mambabuild.py", line 228, in call_conda_build
      result = api.build(
    File "/opt/conda/lib/python3.8/site-packages/conda_build/api.py", line 180, in build
      return build_tree(
    File "/opt/conda/lib/python3.8/site-packages/conda_build/build.py", line 3078, in build_tree
      packages_from_this = build(metadata, stats,
    File "/opt/conda/lib/python3.8/site-packages/conda_build/build.py", line 2038, in build
      output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
    File "/opt/conda/lib/python3.8/site-packages/conda_build/render.py", line 787, in expand_outputs
      for (output_dict, m) in deepcopy(_m).get_output_metadata_set(permit_unsatisfiable_variants=False):
    File "/opt/conda/lib/python3.8/site-packages/conda_build/metadata.py", line 2524, in get_output_metadata_set
      conda_packages = finalize_outputs_pass(
    File "/opt/conda/lib/python3.8/site-packages/conda_build/metadata.py", line 884, in finalize_outputs_pass
      fm = finalize_metadata(
    File "/opt/conda/lib/python3.8/site-packages/conda_build/render.py", line 547, in finalize_metadata
      build_unsat, host_unsat = add_upstream_pins(m,
    File "/opt/conda/lib/python3.8/site-packages/conda_build/render.py", line 409, in add_upstream_pins
      host_deps, host_unsat, extra_run_specs_from_host = _read_upstream_pin_files(m, 'host',
    File "/opt/conda/lib/python3.8/site-packages/conda_build/render.py", line 374, in _read_upstream_pin_files
      deps, actions, unsat = get_env_dependencies(m, env, m.config.variant,
    File "/opt/conda/lib/python3.8/site-packages/conda_build/render.py", line 131, in get_env_dependencies
      actions = environ.get_install_actions(tmpdir, tuple(dependencies), env,
    File "/opt/conda/lib/python3.8/site-packages/boa/cli/mambabuild.py", line 147, in mamba_get_install_actions
      err = DependencyNeedsBuildingError(packages=[str(x) for x in conflict_packages])
    File "/opt/conda/lib/python3.8/site-packages/conda_build/exceptions.py", line 79, in __init__
      raise RuntimeError("failed to parse packages from exception:"
  RuntimeError: failed to parse packages from exception: None
# Last 100 lines of the build log.
