recipe_sha: 694b41c58a7473b8f58902363ac89379a351d7775469e4c4bbfbe07c922220f1  # The commit at which this recipe failed to build.
skiplist: false # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
log: |-
  Warning in writeBin(block[seq_len(min(512L, remain))], out) :
    problem writing to connection
  Warning in writeBin(block[seq_len(min(512L, remain))], out) :
    problem writing to connection
  Warning in writeBin(block[seq_len(min(512L, remain))], out) :
    problem writing to connection
  Warning in writeBin(block[seq_len(min(512L, remain))], out) :
    problem writing to connection
  Warning in writeBin(block[seq_len(min(512L, remain))], out) :
    problem writing to connection
  Warning in writeBin(block[seq_len(min(512L, remain))], out) :
    problem writing to connection
  Warning in writeBin(block[seq_len(min(512L, remain))], out) :
    problem writing to connection
  Warning in writeBin(block[seq_len(min(512L, remain))], out) :
    problem writing to connection
  Warning in writeBin(block[seq_len(min(512L, remain))], out) :
    problem writing to connection
  Warning in writeBin(block[seq_len(min(512L, remain))], out) :
    problem writing to connection
  Warning in writeBin(block[seq_len(min(512L, remain))], out) :
    problem writing to connection
  Warning in writeBin(block[seq_len(min(512L, remain))], out) :
    problem writing to connection
  Warning in writeBin(block[seq_len(min(512L, remain))], out) :
    problem writing to connection
  Warning in writeBin(block[seq_len(min(512L, remain))], out) :
    problem writing to connection
  Warning in writeBin(block[seq_len(min(512L, remain))], out) :
    problem writing to connection
  Warning in writeBin(block[seq_len(min(512L, remain))], out) :
    problem writing to connection
  Warning in writeBin(block[seq_len(min(512L, remain))], out) :
    problem writing to connection
  Warning in writeBin(block[seq_len(min(512L, remain))], out) :
    problem writing to connection
  Warning in writeBin(block[seq_len(min(512L, remain))], out) :
    problem writing to connection
  Warning in writeBin(block[seq_len(min(512L, remain))], out) :
    problem writing to connection
  Warning in writeBin(block[seq_len(min(512L, remain))], out) :
    problem writing to connection
  Warning in writeBin(block[seq_len(min(512L, remain))], out) :
    problem writing to connection
  Warning in writeBin(block[seq_len(min(512L, remain))], out) :
    problem writing to connection
  Warning in writeBin(block[seq_len(min(512L, remain))], out) :
    problem writing to connection
  Warning in writeBin(block[seq_len(min(512L, remain))], out) :
    problem writing to connection
  Warning in writeBin(block[seq_len(min(512L, remain))], out) :
    problem writing to connection
  Warning in writeBin(block[seq_len(min(512L, remain))], out) :
    problem writing to connection
  Warning in writeBin(block[seq_len(min(512L, remain))], out) :
    problem writing to connection
  Warning in writeBin(block[seq_len(min(512L, remain))], out) :
    problem writing to connection
  Warning in writeBin(block[seq_len(min(512L, remain))], out) :
    problem writing to connection
  Warning in writeBin(block[seq_len(min(512L, remain))], out) :
    problem writing to connection
  Warning in close.connection(out) :
    Problem closing connection:  No space left on device
  Warning in dir.create(path, showWarnings = TRUE, recursive = TRUE, ...) :
    cannot create dir 'ChIPXpressData/man', reason 'No space left on device'
  Error in mydir.create(name) :
    failed to create directory ChIPXpressData/man

  return code: 1

  kwargs:
  {}

  : <exception str() failed>

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/opt/conda/bin/conda-mambabuild", line 10, in <module>
      sys.exit(main())
    File "/opt/conda/lib/python3.8/site-packages/boa/cli/mambabuild.py", line 256, in main
      call_conda_build(action, config)
    File "/opt/conda/lib/python3.8/site-packages/boa/cli/mambabuild.py", line 228, in call_conda_build
      result = api.build(
    File "/opt/conda/lib/python3.8/site-packages/conda_build/api.py", line 180, in build
      return build_tree(
    File "/opt/conda/lib/python3.8/site-packages/conda_build/build.py", line 3089, in build_tree
      test(pkg, config=metadata.config.copy(), stats=stats)
    File "/opt/conda/lib/python3.8/site-packages/conda_build/build.py", line 2879, in test
      environ.create_env(metadata.config.test_prefix, actions, config=metadata.config,
    File "/opt/conda/lib/python3.8/site-packages/conda_build/environ.py", line 1068, in create_env
      "too short in" in str(exc)
    File "/opt/conda/lib/python3.8/site-packages/conda/__init__.py", line 104, in __str__
      return "\n".join(str(e) for e in self.errors)  "\n"
    File "/opt/conda/lib/python3.8/site-packages/conda/__init__.py", line 104, in <genexpr>
      return "\n".join(str(e) for e in self.errors)  "\n"
    File "/opt/conda/lib/python3.8/site-packages/conda/__init__.py", line 58, in __str__
      return str(self.message % self._kwargs)
  ValueError: unsupported format character 'T' (0x54) at index 4365
# Last 100 lines of the build log.
